app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return Redirect::route('lists');
});

Route::get('lists', ['as' => 'lists', 'uses' => 'WordsController@lists']);

Route::get('login', 'SessionsController@create');
Route::get('logout', 'SessionsController@destroy');
Route::resource('sessions', 'SessionsController');

Route::resource('words', 'WordsController');

Route::post('conjugations/store/{word_id}', 'ConjugationsController@store');

Route::resource('conjugations', 'ConjugationsController');

Route::get('list/{type}/{subtype?}/{uverbtype?}', ['as' => 'list', 'uses' => 'WordsController@index']);

app/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{{URL::asset('/assets/css/styles.css')}}">
	<script type="text/javascript" src="//code.jquery.com/jquery-2.1.0.min.js"></script>
	<script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="{{URL::asset('/assets/js/japanese.js')}}"></script>
	<title>Japanese</title>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      {{ link_to_route("lists", "Japanese", null, ['class' => 'navbar-brand']) }}
    </div>

	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			@if(Auth::check())
				<li>{{ link_to_route("words.create", "Add") }}</li>
			@endif
		</ul>
	</div>
</nav>

<div class="container col-md-6 col-md-offset-3">
	{{ HTML::decode(link_to(URL::previous(), '<span class="glyphicon glyphicon-arrow-left"></span> back', ['class' => 'btn btn-default'])) }}
     @yield('content')
</div>
	
</body>
</html>